# Unique name for this workflow
name: Custom - Deploy to UAT

# Definition when the workflow should run
on:
    repository_dispatch:
        types: deploy-uat

# Jobs to be executed
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:

            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                ref: ${{ github.event.client_payload.ref }}

            - name: 'Build and Deploy'
              uses: tiagonnascimento/sfdx-orgdev-build-deploy@v1.1
              with:
                type: 'production'
                certificate_path: devops/server.key.enc
                decryption_key: ${{ secrets.DECRYPTION_KEY }}
                decryption_iv: ${{ secrets.DECRYPTION_IV }}
                client_id: ${{ secrets.CONSUMER_KEY_UAT }}
                username: ${{ secrets.USERNAME_UAT }}
                checkonly: false
                manifest_path: manifest/package.xml
