# Unique name for this workflow
name: On push feature - Deploy to Build env

# Definition when the workflow should run
on:
    push:
        branches:
            - feature/*

# Jobs to be executed
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:

            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            - name: 'Build and Deploy'
              uses: tiagonnascimento/sfdx-orgdev-build-deploy@v1.1
              with:
                type: 'production'
                certificate_path: devops/server.key.enc
                decryption_key: ${{ secrets.DECRYPTION_KEY }}
                decryption_iv: ${{ secrets.DECRYPTION_IV }}
                client_id: ${{ secrets.CONSUMER_KEY_BUILD }}
                username: ${{ secrets.USERNAME_BUILD }}
                checkonly: false
                manifest_path: manifest/package.xml